language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install: make install
script: make test
addons:
  sauce_connect: true
env:
  global:
  - secure: HVa+mS1UYk7gI8vl0wLH38tyNP7WumB4HgQ4Zxwshi33Aj8xOvY8ZRSKkv9cufM/t7+r0pe7xk1cZ9Wr36EBIe68CyNWClKnVm90IfkShk6YnTbARjDN8+wdQmtm6MKhi403ByPjJaYN0OCXy4m4s+fWuqCBZOaN3Tp7NCX91bM=
  - secure: Na0duCnYppfPutQuK9TXaLoeEq4QewLFIw30Ga3LhhKqhJXnRd12ddguHUEtA4f4apEIvc4dGUJJsG2AS/Q4Vw1AyUiXMo0gh0iwqpge6zU0RMUb1CD8tQiLYIbyxdWhfHs2X3A8sZzFRvvN0bn97j5lx9b3rDrWpJt448wi9cA=
  - secure: IBzdHjN9p1QzB+Tfs1gR4U1YRLKwu6cX7bSpxLPRqG9N8Vl2aVGmRKWc1F5UIC8GAAywsi4qu7nyHt8tziIU/1IbyA4thb+ObcCClx2JJUpV2Xj/P2WPMDtNFAJkpT8TSJeJ+r2jziBbjmNDa1PisS1OTn9lMaije5w86g4ubZg=
